def get_chain_data():
    return [
        {'name': 'BTC', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/BTC.png', 'shortName': 'btc',
         'chainIndex': '0'},
        {'name': 'Litecoin', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/LTC.png', 'shortName': 'LTC',
         'chainIndex': '2'},
        {'name': 'Ethereum', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/ETH-20220328.png',
         'shortName': 'eth', 'chainIndex': '1'},
        {'name': 'Ethereum Classic', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/ETC.png',
         'shortName': 'ETC', 'chainIndex': '61'},
        {'name': 'Bitcoin Cash', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/BCH.png', 'shortName': 'BCH',
         'chainIndex': '145'},
        {'name': 'Dash', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/dash.png', 'shortName': 'DASH',
         'chainIndex': '5'},
        {'name': 'OKTC', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/okt.png', 'shortName': 'okt',
         'chainIndex': '66'},
        {'name': 'BNB Smart Chain', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/BNB-20220308.png',
         'shortName': 'bsc', 'chainIndex': '56'},
        {'name': 'Avalanche C', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/AVAX.png', 'shortName': 'avax',
         'chainIndex': '43114'},
        {'name': 'Polygon', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/MATIC-20220415.png',
         'shortName': 'matic', 'chainIndex': '137'},
        {'name': 'Fantom', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/FTM-20220328.png', 'shortName': 'ftm',
         'chainIndex': '250'},
        {'name': 'Cronos', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/cro.png', 'shortName': 'Cronos',
         'chainIndex': '25'},
        {'name': 'Kaia Network', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/klay.png', 'shortName': 'Kaia',
         'chainIndex': '8217'},
        {'name': 'KCC', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/kcc.png', 'shortName': 'KCC',
         'chainIndex': '321'},
        {'name': 'Metis', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/metis.png', 'shortName': 'METIS',
         'chainIndex': '1088'},
        {'name': 'Boba', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/boba.png', 'shortName': 'BOBA',
         'chainIndex': '288'},
        {'name': 'Arbitrum One', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/arb_9000.png',
         'shortName': 'Arbitrum', 'chainIndex': '42161'},
        {'name': 'Optimism', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/op_10000.png',
         'shortName': 'Optimism', 'chainIndex': '10'},
        {'name': 'Gnosis', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/xdai_11300.png', 'shortName': 'XDAI',
         'chainIndex': '100'},
        {'name': 'Aurora', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/auroa_11500.png',
         'shortName': 'AURORA', 'chainIndex': '1313161554'},
        {'name': 'Ronin', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/ronin_11800.png', 'shortName': 'RONIN',
         'chainIndex': '2020'},
        {'name': 'Moonbeam', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/moonbeam_12100.png',
         'shortName': 'GLMR', 'chainIndex': '1284'},
        {'name': 'Moonriver', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/movr_12800.png',
         'shortName': 'MOVR', 'chainIndex': '1285'},
        {'name': 'Harmony', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/one_13100.png', 'shortName': 'one',
         'chainIndex': '1666600000'},
        {'name': 'EthereumPoW', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/ETHW.png', 'shortName': 'ETHW',
         'chainIndex': '10001'}, {'name': 'DIS CHAIN',
                                  'logoUrl': 'https://static.coinall.ltd/cdn/web3/currency/token/1707026506326.png/type=png_350_0',
                                  'shortName': 'DIS', 'chainIndex': '513100'},
        {'name': 'Celo', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/celo_16600.png', 'shortName': 'Celo',
         'chainIndex': '42220'},
        {'name': 'zkSync Era', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/zk_17000.png',
         'shortName': 'ZKSync2', 'chainIndex': '324'},
        {'name': 'Flare', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/flr_17300.png', 'shortName': 'Flr',
         'chainIndex': '14'},
        {'name': 'Core', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/core_18300.png', 'shortName': 'core',
         'chainIndex': '1116'},
        {'name': 'Dogecoin', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/18000_doge.png',
         'shortName': 'DOGE', 'chainIndex': '3'},
        {'name': 'Arbitrum Nova', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/nova_18500.png',
         'shortName': 'Nova', 'chainIndex': '42170'},
        {'name': 'Conflux', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/cfx_19200.png', 'shortName': 'cfx',
         'chainIndex': '1030'},
        {'name': 'Polygon zkEVM', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/POLYGON_ETH_19300.png',
         'shortName': 'PolygonZK', 'chainIndex': '1101'},
        {'name': 'Endurance', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/ace_19800.png', 'shortName': 'ACE',
         'chainIndex': '648'},
        {'name': 'Kava EVM', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/evm_kava_19900.png',
         'shortName': 'EVM_KAVA', 'chainIndex': '2222'},
        {'name': 'PulseChain', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/pls_20000.png',
         'shortName': 'PLS', 'chainIndex': '369'},
        {'name': 'Mantle', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/mnt_20100.png', 'shortName': 'Mantle',
         'chainIndex': '5000'},
        {'name': 'Linea', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/linea_eth_20700.png',
         'shortName': 'linea_eth', 'chainIndex': '59144'},
        {'name': 'Base', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/base_20900.png',
         'shortName': 'base_eth', 'chainIndex': '8453'},
        {'name': 'opBNB', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/opbnb_20900.png',
         'shortName': 'op_bnb', 'chainIndex': '204'},
        {'name': 'Sepolia', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/sepolia_eth_21100.png',
         'shortName': 'SEPOLIA_ETH', 'chainIndex': '11155111'},
        {'name': 'HAQQ Network', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/islm_21200.png',
         'shortName': 'HAQQ', 'chainIndex': '11235'},
        {'name': 'Scroll', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/scroll_eth_21400.png',
         'shortName': 'Scroll_eth', 'chainIndex': '534352'},
        {'name': 'Manta Pacific', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/manta_22000.png',
         'shortName': 'Manta', 'chainIndex': '169'},
        {'name': 'Wemix 3.0', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/wemix_22200.png',
         'shortName': 'wemix', 'chainIndex': '1111'},
        {'name': 'Merlin Chain', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/merlin_btc_23400.png',
         'shortName': 'Merlin_Chain', 'chainIndex': '4200'},
        {'name': 'Blast', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/blast_eth_23800.png',
         'shortName': 'Blast', 'chainIndex': '81457'},
        {'name': 'Immutable zkEVM', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/imx_24100.png',
         'shortName': 'Immutable_zkEVM', 'chainIndex': '13371'},
        {'name': 'TRON', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/TRX.png', 'shortName': 'trx',
         'chainIndex': '195'},
        {'name': 'Kroma', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/kroma_28800.png', 'shortName': 'Kroma',
         'chainIndex': '255'},
        {'name': 'X Layer', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/okb_22400.png', 'shortName': 'okb',
         'chainIndex': '196'},
        {'name': 'Taiko Mainnet', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/taiko_26600.png',
         'shortName': 'Taiko', 'chainIndex': '167000'},
        {'name': 'BOB Mainnet', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/bob_26400.png',
         'shortName': 'Bob', 'chainIndex': '60808'},
        {'name': 'Rangers', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/rpg_22600.png', 'shortName': 'rpg',
         'chainIndex': '2025'},
        {'name': 'Mode Network', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/mode_23200.png',
         'shortName': 'Mode_Network', 'chainIndex': '34443'},
        {'name': 'B² Network', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/b2_btc_25500.png',
         'shortName': 'B² Network', 'chainIndex': '223'},
        {'name': 'Bitlayer', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/bitlayer_btc_25600.png',
         'shortName': 'Bitlayer_BTC', 'chainIndex': '200901'}, {'name': 'Fractal Bitcoin',
                                                                'logoUrl': 'https://static.coinall.ltd/cdn/web3/currency/token/1725692491055.png/type=png_350_0',
                                                                'shortName': 'FB', 'chainIndex': '70000061'},
        {'name': 'Sui', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/sui_17700.png', 'shortName': 'Sui',
         'chainIndex': '784'},
        {'name': 'Solana', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/SOL-20220525.png', 'shortName': 'sol',
         'chainIndex': '501'},
        {'name': 'Gravity Alpha', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/g_29600.png',
         'shortName': 'Gravity', 'chainIndex': '1625'},
        {'name': 'Lumi Layer3', 'logoUrl': 'https://static.coinall.ltd/cdn/wallet/logo/lumi_eth_24000.png',
         'shortName': 'Lumi Finance', 'chainIndex': '94168'}
    ]